services:
  db:
    image: mysql:9.5.0
    restart: always
    networks:
      - restaurant_net
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWD_DB}
      MYSQL_USER: ${USER_DB}
      MYSQL_PASSWORD: ${PASSWD_DB}
      MYSQL_DATABASE: ${NAME_DB}
    volumes:
      - restaurant_data:/var/lib/mysql

volumes:
  restaurant_data:

networks:
  restaurant_net:
    driver: bridge